// Generated by validation/scripts/intake-gdps-v021-handoff.mjs. Do not edit.
export const gdpsV021RuntimeRecipeLock = {
  "schemaVersion": "wsgs-gdps-recipe-lock/2.0",
  "providerId": "gdps.geospatial-products",
  "providerVersion": "0.2.1",
  "descriptorRegistryHash": "sha256:5398f91d67fdaafdc0cf552b8613d7ac7229957bb32743fd8bc93d406091d31a",
  "productTypeCount": 34,
  "profileCount": 35,
  "capabilityLockHash": "sha256:d7e15a24bc84723e2ede2a41587d3ab868868ac2e44b7f5d9e39ea3036d1d9f9",
  "recipes": [
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-blocked-areas-in-area",
      "semanticPattern": "GDPS_BLOCKED_AREAS_IN_AREA",
      "requirementType": "FIND_BLOCKED_AREAS",
      "descriptorConstraint": {
        "descriptorId": "UGV_TRAVERSABILITY/DEFAULT",
        "descriptorHash": "sha256:b3395f17c44c4bccca5199e350e3f73be70c1436a40271f8c99c686e9fb182cf"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "traversability.find-blocked",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:7250c16ca6dafdb793ca1f424f598f7ec578ae0953beee8b75aa2fdb18fc8c03",
          "outputSchemaHash": "sha256:27fdc31a5f2949f81c63e0e51646a34adeda4047172da4a5d5f05ed3086ef683",
          "semanticProfileHash": "sha256:7ef17a329e54a881b86a61614d8978304cc4189d43ffd80f20f0b9d7c4968d18"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "UGV_TRAVERSABILITY",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-elevation-at-reference",
      "semanticPattern": "GDPS_ELEVATION_AT_REFERENCE",
      "requirementType": "READ_ELEVATION",
      "descriptorConstraint": {
        "descriptorId": "ELEVATION_DTM/DEFAULT",
        "descriptorHash": "sha256:7e033d18b36916c2e9db8951b3211769dda96244bbfc4d43fc05854f771b93db"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "elevation.sample",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:054650feb398324eb96e49e675c965da197a733a8007995d9febac61c92daf4e",
          "outputSchemaHash": "sha256:03b2019c95ac57880d4453d78188a2f9b9ea51f1d7bd2f5de65b194cae8f2a58",
          "semanticProfileHash": "sha256:af2b429ae0e5a714ad678d523601f3f80549255d6097f3de392ac830d692e02c"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "ELEVATION_DTM",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-find-class",
      "semanticPattern": "GDPS_GENERIC_FIND_CLASS",
      "requirementType": "FIND_GEO_PRODUCT_CLASS_AREAS",
      "descriptorConstraint": null,
      "queryProfile": "FIND_CLASS",
      "allowedOperations": [
        {
          "operationId": "geo-raster.find-by-class",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:14420aab786d8ec86249f284c6f65830f8ab4ffec0e2f4e231bc8c6be544581a",
          "outputSchemaHash": "sha256:1dedcf579484d528a24f692310e4ee43a255e9d465ed2fcb0c7d1a2c4d9b43b3",
          "semanticProfileHash": "sha256:cd43bc2e592a272771a323b34c8e6ee19eb630d51ab6f69460b9cb1444cb3d80"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-find-range",
      "semanticPattern": "GDPS_GENERIC_FIND_RANGE",
      "requirementType": "FIND_GEO_PRODUCT_VALUE_RANGE_AREAS",
      "descriptorConstraint": null,
      "queryProfile": "FIND_VALUE_RANGE",
      "allowedOperations": [
        {
          "operationId": "geo-raster.find-by-range",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:59c10af2dc94a8c6fced44dd8efd5e1b3c42a35b2bbc9b6f152e2ba6f867f3ae",
          "outputSchemaHash": "sha256:e9af4d388195493a247cf3691c2a15d984fd555178c79a84fa4f23261ee9546c",
          "semanticProfileHash": "sha256:219a46103e618fe0ebd68e69ced83dc1660310041eca24f6c4cf04300ca3cf8c"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-profile-value",
      "semanticPattern": "GDPS_GENERIC_PROFILE_VALUE",
      "requirementType": "READ_GEO_PRODUCT_PROFILE",
      "descriptorConstraint": null,
      "queryProfile": "PROFILE_VALUE",
      "allowedOperations": [
        {
          "operationId": "geo-raster.profile",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:cc68b1d5c0c4ba2d787dcb5cb9d1338d23e99793672bb4740629868696e9dc0a",
          "outputSchemaHash": "sha256:2245c2b4c7675cd8e5677e55486565faf65900a6a4343e562b7cc62df6dd97ed",
          "semanticProfileHash": "sha256:57f429907a34fbf2fcccfabc1b691c50f45d506b1a84aa110bd650045b3b4f50"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-sample-value",
      "semanticPattern": "GDPS_GENERIC_SAMPLE_VALUE",
      "requirementType": "READ_GEO_PRODUCT_VALUE",
      "descriptorConstraint": null,
      "queryProfile": "SAMPLE_VALUE_OR_CLASS",
      "allowedOperations": [
        {
          "operationId": "geo-raster.sample",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:57983c08d1fafefac136dc44effa137500bca5580056bd68ec01b677747308d4",
          "outputSchemaHash": "sha256:da086a0ab6c1a48ffeac7633acef50b0385851dbf4e9191c24a21f5cd414ecf0",
          "semanticProfileHash": "sha256:c591c93b448564f1508387ee7609efc6c474fd57fde7c6a2394057cf4fdda4cd"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-vector-in-area",
      "semanticPattern": "GDPS_GENERIC_VECTOR_IN_AREA",
      "requirementType": "FIND_GEO_VECTOR_FEATURES_IN_AREA",
      "descriptorConstraint": null,
      "queryProfile": "VECTOR_IN_AREA",
      "allowedOperations": [
        {
          "operationId": "geo-vector.find-in-area",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:50cc257202bc08ed59edd875c6d10fedd981b5433019890e3fbe26b0dfb5628d",
          "outputSchemaHash": "sha256:6f5bf35c10ddc6abad03063ed907a2852708daf2405c5e7956ca6f33e6bb1651",
          "semanticProfileHash": "sha256:9ce0aba49412495d420c5e3a069a83f3748d883124aa65f34aed800126e40919"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-vector-intersects",
      "semanticPattern": "GDPS_GENERIC_VECTOR_INTERSECTS",
      "requirementType": "FIND_GEO_VECTOR_INTERSECTIONS",
      "descriptorConstraint": null,
      "queryProfile": "VECTOR_INTERSECTS",
      "allowedOperations": [
        {
          "operationId": "geo-vector.find-intersections",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:86d32f555d2af75d5c017ce3cb6494c800648e8fdebedabeb60c9f19cf9e0b16",
          "outputSchemaHash": "sha256:b9955d7e09a5dc5a007c87bdc2f6cd2dabf3a1ffd6df7d37d2df75b20b00dff9",
          "semanticProfileHash": "sha256:5b7a9eb4862d0b459410c2c440a520e8aded8d731fca996d07274bd2a8a89c17"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-generic-vector-nearby",
      "semanticPattern": "GDPS_GENERIC_VECTOR_NEARBY",
      "requirementType": "FIND_GEO_VECTOR_FEATURES_NEARBY",
      "descriptorConstraint": null,
      "queryProfile": "VECTOR_NEARBY",
      "allowedOperations": [
        {
          "operationId": "geo-vector.find-nearby",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:a9d1b2603e28391edcdbe719b7a5ba50eb219e98a15108918ae9dff6a434e391",
          "outputSchemaHash": "sha256:a1df3608bf76e11b79b291db197be30638896a5f56a1395c555a4250233a6d7d",
          "semanticProfileHash": "sha256:5cb080097fe97c67b8bfcdf666be00c8218aa3d35a7dd80604fc707cc0ddde4a"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": null,
        "productProfileConstraint": null,
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-high-ground-in-area",
      "semanticPattern": "GDPS_HIGH_GROUND_IN_AREA",
      "requirementType": "FIND_HIGH_GROUND",
      "descriptorConstraint": {
        "descriptorId": "TERRAIN_FORM/DEFAULT",
        "descriptorHash": "sha256:3c08d74de6b8fe30ee508e8dd42679a40b022f72d83d86d046879bb7be824822"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "terrain.find-high-ground",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:80897dee0dbdbc864d2e302ed65e23b9f34bde167cdb22167ae112bb2fece264",
          "outputSchemaHash": "sha256:b71c4881c6f4b8107dd287f3608230b75cbe23073f1ab674fad0397240525f19",
          "semanticProfileHash": "sha256:ef3e693da1770e1fa4293eb910eb855407569073e22642cef6c3f7112bb1e0e6"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "TERRAIN_FORM",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-land-cover-at-reference",
      "semanticPattern": "GDPS_LAND_COVER_AT_REFERENCE",
      "requirementType": "READ_LAND_COVER",
      "descriptorConstraint": {
        "descriptorId": "LAND_COVER/DEFAULT",
        "descriptorHash": "sha256:7056d986494a8a659bec339ae623b1dba4390358261151ff3fd7aceb33f18599"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "landcover.get-class",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:0eef12b2d785b5b72a9a4efdb61b30f5f50bd3dae47cebdba6a62068111cca39",
          "outputSchemaHash": "sha256:873583ca27a06a82757d9e44476c0da989e1e94787af3c9a9ca9b012acf7e6dd",
          "semanticProfileHash": "sha256:a78ca1f114e3c4de0ad4f497257bcd5a35f3b20789bb997c52a16e6b53a7d6eb"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "LAND_COVER",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-obstacles-near-reference",
      "semanticPattern": "GDPS_OBSTACLES_NEAR_REFERENCE",
      "requirementType": "FIND_OBSTACLES",
      "descriptorConstraint": {
        "descriptorId": "OBSTACLE/DEFAULT",
        "descriptorHash": "sha256:bdaa5c2265dd0b9a039abd647f37f4a7bf9137b556190be71df28172cb1fee74"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "obstacle.find-nearby",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:7f632759afe1c542d164dd3bf6f330d2347fb499997e200c562f3450473f5b78",
          "outputSchemaHash": "sha256:e5cff958e7e0f84e88bc600126462fc29ed97ce2f60cff8ef76c97ecfd46ef41",
          "semanticProfileHash": "sha256:50666af6121815d14b47be71e5969f759dd57eadc496a977e94ad6e8e46a2d5c"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "OBSTACLE",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-traversability-explain-at-reference",
      "semanticPattern": "GDPS_TRAVERSABILITY_EXPLAIN_AT_REFERENCE",
      "requirementType": "EXPLAIN_TRAVERSABILITY",
      "descriptorConstraint": {
        "descriptorId": "UGV_TRAVERSABILITY/DEFAULT",
        "descriptorHash": "sha256:b3395f17c44c4bccca5199e350e3f73be70c1436a40271f8c99c686e9fb182cf"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "traversability.explain",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:bf72fc65e9aa3adb68a80d23fb30c1b4e72c727e6f9aafb6b22464d4c82eb709",
          "outputSchemaHash": "sha256:681ad9732de478d69c1a227e0b586666e32d107fbe848435593036c5d5370d3c",
          "semanticProfileHash": "sha256:d6eb99ab7fa2f3eb231e77c35e0ce02f0c3edfec411ea24f2b0094ca40b3a945"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "UGV_TRAVERSABILITY",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    },
    {
      "schemaVersion": "wsgs-locked-gdps-recipe/2.0",
      "recipeId": "recipe-gdps-wetlands-in-area",
      "semanticPattern": "GDPS_WETLANDS_IN_AREA",
      "requirementType": "FIND_WETLANDS",
      "descriptorConstraint": {
        "descriptorId": "WETLAND/DEFAULT",
        "descriptorHash": "sha256:8918e4e18fa602e8afa62e75c87f765c9b29649a14dbb6ad7b891fe255938800"
      },
      "queryProfile": null,
      "allowedOperations": [
        {
          "operationId": "hydrology.find-wetlands",
          "operationVersion": "1.0",
          "inputSchemaHash": "sha256:7e909d7dd465a9c63eab485bd6b6d1ddee77b1737e2efb66bbe9e3fc825b85cf",
          "outputSchemaHash": "sha256:fe04bcaf65a8cb4c76d41101c555883da93d60aa57d6453f41401bed65fdb289",
          "semanticProfileHash": "sha256:ef3e693da1770e1fa4293eb910eb855407569073e22642cef6c3f7112bb1e0e6"
        }
      ],
      "maturityPolicy": {
        "allowed": "PREVIEW",
        "requiresExactHashes": true
      },
      "productIdPolicy": "UNBOUND_UNLESS_EXPLICIT",
      "inputBindings": {
        "productTypeConstraint": "WETLAND",
        "productProfileConstraint": "DEFAULT",
        "productionProductIdBinding": null,
        "sampleBindingSource": "GDPS_SAMPLE_DATASET_LOCK.json"
      },
      "outputSemantics": {
        "currentOnly": true,
        "noDataIsUnknown": true,
        "snapshotBound": true
      },
      "previewAuthorizationRequired": true
    }
  ]
} as const;
